### ISSUE TITLE
model name should allow dashes

### ISSUE THREAD

**Issue by jon-allen-looker** [fabio-looker/looker_sso_tool#11]
I noticed that my model jonallen-dev is considered invalid by the tool because it contains a dash. I think the tool may need to be modified to allow dashes in the model name.

**Comment by fabio-looker** [comment]
For some reason I didn't see the notification for this!

Someone else reported it to me separately though, so it's been fixed for about a month: https://github.com/fabio-looker/looker_sso_tool/commit/dc5401029fd6b8db9bf6d1373d565cbfdc82c436
