### ISSUE TITLE
please check for invalid port 19999

### ISSUE THREAD

**Issue by pegggggy** [fabio-looker/looker_sso_tool#8]
The port specified on the URL should be the regular looker port, usually 9999, or possibly no port.

when accidentally using port 19999, it gets just far enough to throw an internal error with unhelpful og messages.  The URL fails validation with a signature error.

a simple check for port 19999 would be helpful to catch this error.

**Comment by fabio-looker** [comment]
Got a +1 today, and finally got around to adding this check! 2d880b44c7adcee1a9a2156c06e21879ccb3d6c9
